
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  - statefulsets/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/status
  - services/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - zeebe.zeebe.io
  resources:
  - zeebeclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zeebe.zeebe.io
  resources:
  - zeebeclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - zeebe.zeebe.io
  resources:
  - zeebeprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zeebe.zeebe.io
  resources:
  - zeebeprojects/status
  verbs:
  - get
  - patch
  - update
