apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeebe-operator
  namespace: jx-staging
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: kube-system
  name: pod-lister
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "configmaps"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]  
- apiGroups: ["zeebe.zeebe.io"]
  resources: ["zeebecluster", "zeebeproject"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: jx-staging
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-lister
subjects:
  - kind: ServiceAccount
    name: jx-staging
    namespace: jx-staging